abstract: Perl Module Compilation
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Module-Compile
no_index: 
  directory: 
    - inc
    - t
requires: 
  Digest::SHA1: 0
  perl: 5.6.0
version: 0.20
